artifact_location: file:E:/Github/Machine-Learning-Projects/Computer Vision/Conveyor
  Part Defect Detector/Source Code/runs/mlflow/371158837269195364
creation_time: 1776191687039
experiment_id: '371158837269195364'
last_update_time: 1776191687039
lifecycle_stage: active
name: E:\Github\Machine-Learning-Projects\Computer Vision\Conveyor Part Defect Detector\Source
  Code\runs
trace_location: null
workspace: default
