"""
Tests for: Machine Learning Projects 138 - Customer_Segmentation_Online_Retail
Auto-generated by Phase 4 test generator.
"""
import pytest
import numpy as np
import pandas as pd
from pathlib import Path

DATA_DIR = Path(__file__).resolve().parent.parent / "data" / "customer_segmentation_online_retail"
pytestmark = []
pytestmark.append(pytest.mark.data)
pytestmark.append(pytest.mark.eda)


class TestDataLoading:
    """Verify dataset loads correctly."""

    def test_data_dir_exists(self):
        if not DATA_DIR.exists():
            pytest.skip(f"Data directory not found: {DATA_DIR}")
        assert DATA_DIR.exists()

    def test_data_file_exists(self):
        if not DATA_DIR.exists():
            pytest.skip("Data directory missing")
        fpath = DATA_DIR / "Online Retail.xlsx"
        if not fpath.exists():
            pytest.skip(f"Data file not found: {fpath}")
        assert fpath.exists()

    def test_load_without_error(self):
        fpath = DATA_DIR / "Online Retail.xlsx"
        if not fpath.exists():
            pytest.skip(f"Data file not found: {fpath}")
        try:
            df = pd.read_excel(DATA_DIR / "Online Retail.xlsx")
        except (UnicodeDecodeError, ValueError):
            df = pd.read_excel(DATA_DIR / "Online Retail.xlsx", encoding="latin-1")
        assert df is not None

    def test_dataframe_not_empty(self):
        fpath = DATA_DIR / "Online Retail.xlsx"
        if not fpath.exists():
            pytest.skip(f"Data file not found: {fpath}")
        try:
            df = pd.read_excel(DATA_DIR / "Online Retail.xlsx")
        except (UnicodeDecodeError, ValueError):
            df = pd.read_excel(DATA_DIR / "Online Retail.xlsx", encoding="latin-1")
        assert len(df) > 0, "DataFrame is empty"
        assert df.shape[1] > 0, "DataFrame has no columns"

    def test_no_all_null_columns(self):
        fpath = DATA_DIR / "Online Retail.xlsx"
        if not fpath.exists():
            pytest.skip(f"Data file not found: {fpath}")
        try:
            df = pd.read_excel(DATA_DIR / "Online Retail.xlsx")
        except (UnicodeDecodeError, ValueError):
            df = pd.read_excel(DATA_DIR / "Online Retail.xlsx", encoding="latin-1")
        # Filter out trailing "Unnamed:" columns (common CSV artifact)
        real_cols = [c for c in df.columns if not str(c).startswith("Unnamed:")]
        if not real_cols:
            pytest.skip("All columns are unnamed — likely metadata file")
        null_cols = [col for col in real_cols if df[col].isna().all()]
        assert len(null_cols) == 0, f"All-NaN columns: {null_cols}"


class TestPreprocessing:
    """Verify preprocessing steps work correctly."""


    def test_numpy_operations(self):
        import numpy as np
        arr = np.array([1, 2, 3, 4, 5])
        assert arr.mean() == 3.0
        assert arr.std() > 0


class TestModelTraining:
    """EDA/conceptual project — no model training tests needed."""

    def test_pandas_available(self):
        import pandas as pd
        assert pd.__version__ is not None

    def test_numpy_available(self):
        import numpy as np
        assert np.__version__ is not None


class TestPrediction:
    """EDA/conceptual project — no prediction tests needed."""

    def test_placeholder(self):
        # This project is EDA/conceptual only — no model to predict with
        assert True

