"""
Tests for: Machine Learning Projects  85 -Sentiment Analysis - Restaurant Reviews
Auto-generated by Phase 4 test generator.
"""
import pytest
import numpy as np
import pandas as pd
from pathlib import Path

DATA_DIR = Path(__file__).resolve().parent.parent / "data" / "sentiment_analysis_-_restaurant_reviews"
pytestmark = []
pytestmark.append(pytest.mark.data)
pytestmark.append(pytest.mark.nlp)


class TestDataLoading:
    """Verify dataset loads correctly."""

    def test_data_dir_exists(self):
        if not DATA_DIR.exists():
            pytest.skip(f"Data directory not found: {DATA_DIR}")
        assert DATA_DIR.exists()

    def test_data_file_exists(self):
        if not DATA_DIR.exists():
            pytest.skip("Data directory missing")
        fpath = DATA_DIR / "Restaurant_Reviews.tsv"
        if not fpath.exists():
            pytest.skip(f"Data file not found: {fpath}")
        assert fpath.exists()

    def test_load_without_error(self):
        fpath = DATA_DIR / "Restaurant_Reviews.tsv"
        if not fpath.exists():
            pytest.skip(f"Data file not found: {fpath}")
        try:
            df = pd.read_csv(DATA_DIR / "Restaurant_Reviews.tsv", sep="\t")
        except (UnicodeDecodeError, ValueError):
            df = pd.read_csv(DATA_DIR / "Restaurant_Reviews.tsv", encoding="latin-1", sep="\t")
        assert df is not None

    def test_dataframe_not_empty(self):
        fpath = DATA_DIR / "Restaurant_Reviews.tsv"
        if not fpath.exists():
            pytest.skip(f"Data file not found: {fpath}")
        try:
            df = pd.read_csv(DATA_DIR / "Restaurant_Reviews.tsv", sep="\t")
        except (UnicodeDecodeError, ValueError):
            df = pd.read_csv(DATA_DIR / "Restaurant_Reviews.tsv", encoding="latin-1", sep="\t")
        assert len(df) > 0, "DataFrame is empty"
        assert df.shape[1] > 0, "DataFrame has no columns"

    def test_no_all_null_columns(self):
        fpath = DATA_DIR / "Restaurant_Reviews.tsv"
        if not fpath.exists():
            pytest.skip(f"Data file not found: {fpath}")
        try:
            df = pd.read_csv(DATA_DIR / "Restaurant_Reviews.tsv", sep="\t")
        except (UnicodeDecodeError, ValueError):
            df = pd.read_csv(DATA_DIR / "Restaurant_Reviews.tsv", encoding="latin-1", sep="\t")
        # Filter out trailing "Unnamed:" columns (common CSV artifact)
        real_cols = [c for c in df.columns if not str(c).startswith("Unnamed:")]
        if not real_cols:
            pytest.skip("All columns are unnamed — likely metadata file")
        null_cols = [col for col in real_cols if df[col].isna().all()]
        assert len(null_cols) == 0, f"All-NaN columns: {null_cols}"


class TestPreprocessing:
    """Verify preprocessing steps work correctly."""


    def test_text_vectorizer(self):
        from sklearn.feature_extraction.text import CountVectorizer
        corpus = ["hello world", "world is great", "hello great world"]
        vec = CountVectorizer()
        X = vec.fit_transform(corpus)
        assert X.shape[0] == 3
        assert X.shape[1] > 0


    def test_train_test_split(self):
        from sklearn.model_selection import train_test_split
        import numpy as np
        X = np.random.randn(100, 5)
        y = np.random.randint(0, 2, 100)
        X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
        assert len(X_train) == 80
        assert len(X_test) == 20
        assert X_train.shape[1] == 5


class TestModelTraining:
    """Verify model training pipeline."""

    def test_model_instantiation(self):
        from sklearn.naive_bayes import MultinomialNB
        model = MultinomialNB()
        assert model is not None
        assert hasattr(model, "fit")
        assert hasattr(model, "predict")

    def test_model_fit(self):
        from sklearn.naive_bayes import MultinomialNB
        import numpy as np
        X = np.abs(np.random.randn(100, 5))
        y = np.random.randint(0, 2, 100)
        model = MultinomialNB()
        model.fit(X, y)
        assert hasattr(model, "predict")

    def test_model_score(self):
        from sklearn.naive_bayes import MultinomialNB
        from sklearn.metrics import accuracy_score
        import numpy as np
        X = np.abs(np.random.randn(200, 5))
        y = np.random.randint(0, 2, 200)
        model = MultinomialNB()
        model.fit(X[:150], y[:150])
        preds = model.predict(X[150:])
        score = accuracy_score(y[150:], preds)
        assert 0.0 <= score <= 1.0


class TestPrediction:
    """Verify prediction outputs."""

    def test_prediction_shape(self):
        from sklearn.naive_bayes import MultinomialNB
        import numpy as np
        X = np.abs(np.random.randn(200, 5))
        y = np.random.randint(0, 2, 200)
        model = MultinomialNB()
        model.fit(X[:150], y[:150])
        preds = model.predict(X[150:])
        assert preds.shape == (50,)

    def test_prediction_type(self):
        from sklearn.naive_bayes import MultinomialNB
        import numpy as np
        X = np.abs(np.random.randn(200, 5))
        y = np.random.randint(0, 2, 200)
        model = MultinomialNB()
        model.fit(X[:150], y[:150])
        preds = model.predict(X[150:])
        assert preds.dtype in [np.int32, np.int64, np.float64, np.float32]

    def test_no_nan_predictions(self):
        from sklearn.naive_bayes import MultinomialNB
        import numpy as np
        X = np.abs(np.random.randn(200, 5))
        y = np.random.randint(0, 2, 200)
        model = MultinomialNB()
        model.fit(X[:150], y[:150])
        preds = model.predict(X[150:])
        assert not np.any(np.isnan(preds))

