"""
Tests for: Machine Learning Projects 125 - Text Classification keras_consumer_complaints
Auto-generated by Phase 4 test generator.
"""
import pytest
import numpy as np
import pandas as pd
from pathlib import Path

DATA_DIR = Path(__file__).resolve().parent.parent / "data" / "text_classification_keras_consumer_complaints"
pytestmark = []
pytestmark.append(pytest.mark.data)
pytestmark.append(pytest.mark.cv)
pytestmark.append(pytest.mark.slow)
pytestmark.append(pytest.mark.keras)
pytestmark.append(pytest.mark.slow)


class TestDataLoading:
    """Verify data is available."""

    def test_data_dir_exists(self):
        if not DATA_DIR.exists():
            pytest.skip(f"Data directory not found: {DATA_DIR}")
        assert DATA_DIR.exists()


class TestPreprocessing:
    """Verify preprocessing steps work correctly."""


    def test_train_test_split(self):
        from sklearn.model_selection import train_test_split
        import numpy as np
        X = np.random.randn(100, 5)
        y = np.random.randint(0, 2, 100)
        X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
        assert len(X_train) == 80
        assert len(X_test) == 20
        assert X_train.shape[1] == 5


class TestModelTraining:
    """Verify Keras model pipeline."""

    def test_keras_importable(self):
        try:
            from tensorflow import keras
        except ImportError:
            pytest.skip("tensorflow not installed")

    def test_model_build(self):
        try:
            from tensorflow.keras.models import Sequential
            from tensorflow.keras.layers import Dense, Flatten, Conv2D, MaxPooling2D
        except ImportError:
            pytest.skip("tensorflow not installed")
        model = Sequential([
            Conv2D(8, (3, 3), activation="relu", input_shape=(32, 32, 3)),
            MaxPooling2D((2, 2)),
            Flatten(),
            Dense(16, activation="relu"),
            Dense(2, activation="softmax"),
        ])
        model.compile(optimizer="adam", loss="sparse_categorical_crossentropy", metrics=["accuracy"])
        assert model is not None
        assert len(model.layers) == 5

    def test_model_predict_shape(self):
        try:
            from tensorflow.keras.models import Sequential
            from tensorflow.keras.layers import Dense, Flatten, Conv2D, MaxPooling2D
        except ImportError:
            pytest.skip("tensorflow not installed")
        import numpy as np
        model = Sequential([
            Conv2D(8, (3, 3), activation="relu", input_shape=(32, 32, 3)),
            MaxPooling2D((2, 2)),
            Flatten(),
            Dense(16, activation="relu"),
            Dense(2, activation="softmax"),
        ])
        model.compile(optimizer="adam", loss="sparse_categorical_crossentropy")
        X_dummy = np.random.randn(5, 32, 32, 3).astype(np.float32)
        preds = model.predict(X_dummy, verbose=0)
        assert preds.shape == (5, 2)


class TestPrediction:
    """Verify prediction outputs."""

    def test_predictions_sum_to_one(self):
        try:
            from tensorflow.keras.models import Sequential
            from tensorflow.keras.layers import Dense, Flatten, Conv2D, MaxPooling2D
        except ImportError:
            pytest.skip("tensorflow not installed")
        import numpy as np
        model = Sequential([
            Conv2D(8, (3, 3), activation="relu", input_shape=(32, 32, 3)),
            MaxPooling2D((2, 2)),
            Flatten(),
            Dense(16, activation="relu"),
            Dense(2, activation="softmax"),
        ])
        model.compile(optimizer="adam", loss="sparse_categorical_crossentropy")
        X_dummy = np.random.randn(5, 32, 32, 3).astype(np.float32)
        preds = model.predict(X_dummy, verbose=0)
        for row in preds:
            assert abs(row.sum() - 1.0) < 1e-5

