"""
Tests for: Machine Learning Project 16 - Flower Species Classification
Auto-generated by Phase 4 test generator.
"""
import pytest
import numpy as np
import pandas as pd
from pathlib import Path

DATA_DIR = Path(__file__).resolve().parent.parent / "data" / "flower_species_classification"
pytestmark = []
pytestmark.append(pytest.mark.cv)
pytestmark.append(pytest.mark.slow)


class TestDataLoading:
    """Verify seaborn dataset loads."""

    def test_load_seaborn_dataset(self):
        try:
            import seaborn as sns
        except ImportError:
            pytest.skip("seaborn not installed")
        df = sns.load_dataset("iris")
        assert len(df) > 0


class TestPreprocessing:
    """Verify preprocessing steps work correctly."""


    def test_scaler_fit_transform(self):
        from sklearn.preprocessing import StandardScaler
        import numpy as np
        X = np.random.randn(100, 5)
        scaler = StandardScaler()
        X_scaled = scaler.fit_transform(X)
        assert X_scaled.shape == X.shape
        assert not np.any(np.isnan(X_scaled))


    def test_train_test_split(self):
        from sklearn.model_selection import train_test_split
        import numpy as np
        X = np.random.randn(100, 5)
        y = np.random.randint(0, 2, 100)
        X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
        assert len(X_train) == 80
        assert len(X_test) == 20
        assert X_train.shape[1] == 5


class TestModelTraining:
    """Verify model training pipeline."""

    def test_model_instantiation(self):
        from sklearn.linear_model import LogisticRegression
        model = LogisticRegression()
        assert model is not None
        assert hasattr(model, "fit")
        assert hasattr(model, "predict")

    def test_model_fit(self):
        from sklearn.linear_model import LogisticRegression
        import numpy as np
        X = np.random.randn(100, 5)
        y = np.random.randint(0, 2, 100)
        model = LogisticRegression()
        model.fit(X, y)
        assert hasattr(model, "predict")

    def test_model_score(self):
        from sklearn.linear_model import LogisticRegression
        from sklearn.metrics import accuracy_score
        import numpy as np
        X = np.random.randn(200, 5)
        y = np.random.randint(0, 2, 200)
        model = LogisticRegression()
        model.fit(X[:150], y[:150])
        preds = model.predict(X[150:])
        score = accuracy_score(y[150:], preds)
        assert 0.0 <= score <= 1.0


class TestPrediction:
    """Verify prediction outputs."""

    def test_prediction_shape(self):
        from sklearn.linear_model import LogisticRegression
        import numpy as np
        X = np.random.randn(200, 5)
        y = np.random.randint(0, 2, 200)
        model = LogisticRegression()
        model.fit(X[:150], y[:150])
        preds = model.predict(X[150:])
        assert preds.shape == (50,)

    def test_prediction_type(self):
        from sklearn.linear_model import LogisticRegression
        import numpy as np
        X = np.random.randn(200, 5)
        y = np.random.randint(0, 2, 200)
        model = LogisticRegression()
        model.fit(X[:150], y[:150])
        preds = model.predict(X[150:])
        assert preds.dtype in [np.int32, np.int64, np.float64, np.float32]

    def test_no_nan_predictions(self):
        from sklearn.linear_model import LogisticRegression
        import numpy as np
        X = np.random.randn(200, 5)
        y = np.random.randint(0, 2, 200)
        model = LogisticRegression()
        model.fit(X[:150], y[:150])
        preds = model.predict(X[150:])
        assert not np.any(np.isnan(preds))

