"""
Tests for: Machine Learning Projects  87 - Clustering - KMeans Clustering for Imagery Analysis
Auto-generated by Phase 4 test generator.
"""
import pytest
import numpy as np
import pandas as pd
from pathlib import Path

DATA_DIR = Path(__file__).resolve().parent.parent / "data" / "clustering_-_kmeans_clustering_for_imagery_analysis"
pytestmark = []
pytestmark.append(pytest.mark.data)
pytestmark.append(pytest.mark.clustering)


class TestDataLoading:
    """Verify binary/image data file exists and loads."""

    def test_data_dir_exists(self):
        if not DATA_DIR.exists():
            pytest.skip(f"Data directory not found: {DATA_DIR}")
        assert DATA_DIR.exists()

    def test_data_file_exists(self):
        if not DATA_DIR.exists():
            pytest.skip("Data directory missing")
        fpath = DATA_DIR / "mnist.npz"
        if not fpath.exists():
            pytest.skip(f"Data file not found: {fpath}")
        assert fpath.exists()

    def test_load_without_error(self):
        fpath = DATA_DIR / "mnist.npz"
        if not fpath.exists():
            pytest.skip(f"Data file not found: {fpath}")
        import numpy as np
        data = np.load(DATA_DIR / "mnist.npz", allow_pickle=True)
        assert len(data.files) > 0, "NPZ archive has no arrays"


class TestPreprocessing:
    """Verify preprocessing steps work correctly."""


    def test_numpy_operations(self):
        import numpy as np
        arr = np.array([1, 2, 3, 4, 5])
        assert arr.mean() == 3.0
        assert arr.std() > 0


class TestModelTraining:
    """Verify model training pipeline."""

    def test_model_instantiation(self):
        from sklearn.cluster import KMeans
        model = KMeans(n_clusters=3)
        assert model is not None

    def test_model_fit(self):
        from sklearn.cluster import KMeans
        import numpy as np
        X = np.random.randn(100, 5)
        model = KMeans(n_clusters=3)
        model.fit(X)
        assert hasattr(model, "labels_")
        assert len(model.labels_) == 100

    def test_prediction(self):
        from sklearn.cluster import KMeans
        import numpy as np
        X = np.random.randn(100, 5)
        model = KMeans(n_clusters=3)
        model.fit(X)
        labels = model.predict(X[:10])
        assert labels.shape == (10,)
        assert all(0 <= l < 3 for l in labels)


class TestPrediction:
    """Verify prediction outputs."""

    def test_prediction_shape(self):
        from sklearn.cluster import KMeans
        import numpy as np
        X = np.random.randn(200, 5)
        model = KMeans(n_clusters=3)
        model.fit(X)
        preds = model.predict(X[:50])
        assert preds.shape == (50,)

    def test_prediction_type(self):
        from sklearn.cluster import KMeans
        import numpy as np
        X = np.random.randn(200, 5)
        model = KMeans(n_clusters=3)
        model.fit(X)
        preds = model.predict(X[:10])
        assert preds.dtype in [np.int32, np.int64, np.float64, np.float32]

