"""
Tests for: Machine Learning Projects 74 - digit_recognition-mnist-sequence
Auto-generated by Phase 4 test generator.
"""
import pytest
import numpy as np
import pandas as pd
from pathlib import Path

DATA_DIR = Path(__file__).resolve().parent.parent / "data" / "digit_recognition-mnist-sequence"
pytestmark = []
pytestmark.append(pytest.mark.data)
pytestmark.append(pytest.mark.cv)
pytestmark.append(pytest.mark.slow)
pytestmark.append(pytest.mark.keras)
pytestmark.append(pytest.mark.slow)


class TestDataLoading:
    """Verify dataset loads correctly."""

    def test_data_dir_exists(self):
        if not DATA_DIR.exists():
            pytest.skip(f"Data directory not found: {DATA_DIR}")
        assert DATA_DIR.exists()

    def test_data_file_exists(self):
        if not DATA_DIR.exists():
            pytest.skip("Data directory missing")
        fpath = DATA_DIR / "911.csv"
        if not fpath.exists():
            pytest.skip(f"Data file not found: {fpath}")
        assert fpath.exists()

    def test_load_without_error(self):
        fpath = DATA_DIR / "911.csv"
        if not fpath.exists():
            pytest.skip(f"Data file not found: {fpath}")
        try:
            df = pd.read_csv(DATA_DIR / "911.csv")
        except (UnicodeDecodeError, ValueError):
            df = pd.read_csv(DATA_DIR / "911.csv", encoding="latin-1")
        assert df is not None

    def test_dataframe_not_empty(self):
        fpath = DATA_DIR / "911.csv"
        if not fpath.exists():
            pytest.skip(f"Data file not found: {fpath}")
        try:
            df = pd.read_csv(DATA_DIR / "911.csv")
        except (UnicodeDecodeError, ValueError):
            df = pd.read_csv(DATA_DIR / "911.csv", encoding="latin-1")
        assert len(df) > 0, "DataFrame is empty"
        assert df.shape[1] > 0, "DataFrame has no columns"

    def test_no_all_null_columns(self):
        fpath = DATA_DIR / "911.csv"
        if not fpath.exists():
            pytest.skip(f"Data file not found: {fpath}")
        try:
            df = pd.read_csv(DATA_DIR / "911.csv")
        except (UnicodeDecodeError, ValueError):
            df = pd.read_csv(DATA_DIR / "911.csv", encoding="latin-1")
        # Filter out trailing "Unnamed:" columns (common CSV artifact)
        real_cols = [c for c in df.columns if not str(c).startswith("Unnamed:")]
        if not real_cols:
            pytest.skip("All columns are unnamed — likely metadata file")
        null_cols = [col for col in real_cols if df[col].isna().all()]
        assert len(null_cols) == 0, f"All-NaN columns: {null_cols}"


class TestPreprocessing:
    """Verify preprocessing steps work correctly."""


    def test_numpy_operations(self):
        import numpy as np
        arr = np.array([1, 2, 3, 4, 5])
        assert arr.mean() == 3.0
        assert arr.std() > 0


class TestModelTraining:
    """Verify Keras model pipeline."""

    def test_keras_importable(self):
        try:
            from tensorflow import keras
        except ImportError:
            pytest.skip("tensorflow not installed")

    def test_model_build(self):
        try:
            from tensorflow.keras.models import Sequential
            from tensorflow.keras.layers import Dense, Flatten, Conv2D, MaxPooling2D
        except ImportError:
            pytest.skip("tensorflow not installed")
        model = Sequential([
            Conv2D(8, (3, 3), activation="relu", input_shape=(32, 32, 3)),
            MaxPooling2D((2, 2)),
            Flatten(),
            Dense(16, activation="relu"),
            Dense(2, activation="softmax"),
        ])
        model.compile(optimizer="adam", loss="sparse_categorical_crossentropy", metrics=["accuracy"])
        assert model is not None
        assert len(model.layers) == 5

    def test_model_predict_shape(self):
        try:
            from tensorflow.keras.models import Sequential
            from tensorflow.keras.layers import Dense, Flatten, Conv2D, MaxPooling2D
        except ImportError:
            pytest.skip("tensorflow not installed")
        import numpy as np
        model = Sequential([
            Conv2D(8, (3, 3), activation="relu", input_shape=(32, 32, 3)),
            MaxPooling2D((2, 2)),
            Flatten(),
            Dense(16, activation="relu"),
            Dense(2, activation="softmax"),
        ])
        model.compile(optimizer="adam", loss="sparse_categorical_crossentropy")
        X_dummy = np.random.randn(5, 32, 32, 3).astype(np.float32)
        preds = model.predict(X_dummy, verbose=0)
        assert preds.shape == (5, 2)


class TestPrediction:
    """Verify prediction outputs."""

    def test_predictions_sum_to_one(self):
        try:
            from tensorflow.keras.models import Sequential
            from tensorflow.keras.layers import Dense, Flatten, Conv2D, MaxPooling2D
        except ImportError:
            pytest.skip("tensorflow not installed")
        import numpy as np
        model = Sequential([
            Conv2D(8, (3, 3), activation="relu", input_shape=(32, 32, 3)),
            MaxPooling2D((2, 2)),
            Flatten(),
            Dense(16, activation="relu"),
            Dense(2, activation="softmax"),
        ])
        model.compile(optimizer="adam", loss="sparse_categorical_crossentropy")
        X_dummy = np.random.randn(5, 32, 32, 3).astype(np.float32)
        preds = model.predict(X_dummy, verbose=0)
        for row in preds:
            assert abs(row.sum() - 1.0) < 1e-5

