"""
Tests for: Machine Learning Projects 155 - Captcha Recognition
Auto-generated by Phase 4 test generator.
"""
import pytest
import numpy as np
import pandas as pd
from pathlib import Path

DATA_DIR = Path(__file__).resolve().parent.parent / "data" / "captcha_recognition"
pytestmark = []
pytestmark.append(pytest.mark.data)
pytestmark.append(pytest.mark.cv)
pytestmark.append(pytest.mark.slow)
pytestmark.append(pytest.mark.keras)
pytestmark.append(pytest.mark.slow)


class TestDataLoading:
    """Verify image dataset structure."""

    def test_data_dir_exists(self):
        if not DATA_DIR.exists():
            pytest.skip(f"Data directory not found: {DATA_DIR}")
        assert DATA_DIR.exists()

    def test_has_subdirectories(self):
        if not DATA_DIR.exists():
            pytest.skip("Data directory missing")
        subdirs = [d for d in DATA_DIR.rglob("*") if d.is_dir()]
        if not subdirs:
            pytest.skip("No subdirectories — may need dataset download")
        assert len(subdirs) > 0

    def test_contains_images(self):
        if not DATA_DIR.exists():
            pytest.skip("Data directory missing")
        image_exts = {".jpg", ".jpeg", ".png", ".bmp", ".gif", ".tif", ".tiff"}
        found = any(p.suffix.lower() in image_exts for p in DATA_DIR.rglob("*"))
        if not found:
            pytest.skip("No images found — may need dataset download")
        assert found

    def test_sample_image_loadable(self):
        if not DATA_DIR.exists():
            pytest.skip("Data directory missing")
        from PIL import Image
        image_exts = {".jpg", ".jpeg", ".png", ".bmp", ".gif"}
        for p in DATA_DIR.rglob("*"):
            if p.suffix.lower() in image_exts:
                img = Image.open(p)
                assert img.size[0] > 0 and img.size[1] > 0
                return
        pytest.skip("No images to test")


class TestPreprocessing:
    """Verify preprocessing steps work correctly."""


    def test_numpy_operations(self):
        import numpy as np
        arr = np.array([1, 2, 3, 4, 5])
        assert arr.mean() == 3.0
        assert arr.std() > 0


class TestModelTraining:
    """Verify Keras model pipeline."""

    def test_keras_importable(self):
        try:
            from tensorflow import keras
        except ImportError:
            pytest.skip("tensorflow not installed")

    def test_model_build(self):
        try:
            from tensorflow.keras.models import Sequential
            from tensorflow.keras.layers import Dense, Flatten, Conv2D, MaxPooling2D
        except ImportError:
            pytest.skip("tensorflow not installed")
        model = Sequential([
            Conv2D(8, (3, 3), activation="relu", input_shape=(32, 32, 3)),
            MaxPooling2D((2, 2)),
            Flatten(),
            Dense(16, activation="relu"),
            Dense(2, activation="softmax"),
        ])
        model.compile(optimizer="adam", loss="sparse_categorical_crossentropy", metrics=["accuracy"])
        assert model is not None
        assert len(model.layers) == 5

    def test_model_predict_shape(self):
        try:
            from tensorflow.keras.models import Sequential
            from tensorflow.keras.layers import Dense, Flatten, Conv2D, MaxPooling2D
        except ImportError:
            pytest.skip("tensorflow not installed")
        import numpy as np
        model = Sequential([
            Conv2D(8, (3, 3), activation="relu", input_shape=(32, 32, 3)),
            MaxPooling2D((2, 2)),
            Flatten(),
            Dense(16, activation="relu"),
            Dense(2, activation="softmax"),
        ])
        model.compile(optimizer="adam", loss="sparse_categorical_crossentropy")
        X_dummy = np.random.randn(5, 32, 32, 3).astype(np.float32)
        preds = model.predict(X_dummy, verbose=0)
        assert preds.shape == (5, 2)


class TestPrediction:
    """Verify prediction outputs."""

    def test_predictions_sum_to_one(self):
        try:
            from tensorflow.keras.models import Sequential
            from tensorflow.keras.layers import Dense, Flatten, Conv2D, MaxPooling2D
        except ImportError:
            pytest.skip("tensorflow not installed")
        import numpy as np
        model = Sequential([
            Conv2D(8, (3, 3), activation="relu", input_shape=(32, 32, 3)),
            MaxPooling2D((2, 2)),
            Flatten(),
            Dense(16, activation="relu"),
            Dense(2, activation="softmax"),
        ])
        model.compile(optimizer="adam", loss="sparse_categorical_crossentropy")
        X_dummy = np.random.randn(5, 32, 32, 3).astype(np.float32)
        preds = model.predict(X_dummy, verbose=0)
        for row in preds:
            assert abs(row.sum() - 1.0) < 1e-5

