"""
Tests for: Machine Learning Projects 148 -U.S. Gasoline and Diesel Retail Prices 1995-2021
Auto-generated by Phase 4 test generator.
"""
import pytest
import numpy as np
import pandas as pd
from pathlib import Path

DATA_DIR = Path(__file__).resolve().parent.parent / "data" / "us_gasoline_and_diesel_retail_prices_1995-2021"
pytestmark = []
pytestmark.append(pytest.mark.data)
pytestmark.append(pytest.mark.sklearn)


class TestDataLoading:
    """Verify data is available."""

    def test_data_dir_exists(self):
        if not DATA_DIR.exists():
            pytest.skip(f"Data directory not found: {DATA_DIR}")
        assert DATA_DIR.exists()


class TestPreprocessing:
    """Verify preprocessing steps work correctly."""


    def test_scaler_fit_transform(self):
        from sklearn.preprocessing import MinMaxScaler
        import numpy as np
        X = np.random.randn(100, 5)
        scaler = MinMaxScaler()
        X_scaled = scaler.fit_transform(X)
        assert X_scaled.shape == X.shape
        assert not np.any(np.isnan(X_scaled))


    def test_train_test_split(self):
        from sklearn.model_selection import train_test_split
        import numpy as np
        X = np.random.randn(100, 5)
        y = np.random.randint(0, 2, 100)
        X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
        assert len(X_train) == 80
        assert len(X_test) == 20
        assert X_train.shape[1] == 5


class TestModelTraining:
    """Verify model training pipeline."""

    def test_model_instantiation(self):
        from sklearn.linear_model import LinearRegression
        model = LinearRegression()
        assert model is not None
        assert hasattr(model, "fit")
        assert hasattr(model, "predict")

    def test_model_fit(self):
        from sklearn.linear_model import LinearRegression
        import numpy as np
        X = np.random.randn(100, 5)
        y = np.random.randn(100)
        model = LinearRegression()
        model.fit(X, y)
        assert hasattr(model, "predict")

    def test_model_r2(self):
        from sklearn.linear_model import LinearRegression
        from sklearn.metrics import r2_score
        import numpy as np
        np.random.seed(42)
        X = np.random.randn(200, 5)
        y = X @ np.array([1, 2, 3, 4, 5]) + np.random.randn(200) * 0.1
        model = LinearRegression()
        model.fit(X[:150], y[:150])
        preds = model.predict(X[150:])
        r2 = r2_score(y[150:], preds)
        assert r2 > 0.5  # should fit well on linear data


class TestPrediction:
    """Verify prediction outputs."""

    def test_prediction_shape(self):
        from sklearn.linear_model import LinearRegression
        import numpy as np
        X = np.random.randn(200, 5)
        y = np.random.randn(200)
        model = LinearRegression()
        model.fit(X[:150], y[:150])
        preds = model.predict(X[150:])
        assert preds.shape == (50,)

    def test_predictions_are_numeric(self):
        from sklearn.linear_model import LinearRegression
        import numpy as np
        X = np.random.randn(200, 5)
        y = np.random.randn(200)
        model = LinearRegression()
        model.fit(X[:150], y[:150])
        preds = model.predict(X[150:])
        assert np.issubdtype(preds.dtype, np.floating) or np.issubdtype(preds.dtype, np.integer)

    def test_no_nan_predictions(self):
        from sklearn.linear_model import LinearRegression
        import numpy as np
        X = np.random.randn(200, 5)
        y = np.random.randn(200)
        model = LinearRegression()
        model.fit(X[:150], y[:150])
        preds = model.predict(X[150:])
        assert not np.any(np.isnan(preds))

