"""
Tests for: Machine Learning Projects 126 - Time Series Forecastings
Auto-generated by Phase 4 test generator.
"""
import pytest
import numpy as np
import pandas as pd
from pathlib import Path

DATA_DIR = Path(__file__).resolve().parent.parent / "data" / "time_series_forecastings"
pytestmark = []
pytestmark.append(pytest.mark.data)
pytestmark.append(pytest.mark.sklearn)


class TestDataLoading:
    """Verify dataset loads correctly."""

    def test_data_dir_exists(self):
        if not DATA_DIR.exists():
            pytest.skip(f"Data directory not found: {DATA_DIR}")
        assert DATA_DIR.exists()

    def test_data_file_exists(self):
        if not DATA_DIR.exists():
            pytest.skip("Data directory missing")
        fpath = DATA_DIR / "Sample - Superstore.xls"
        if not fpath.exists():
            pytest.skip(f"Data file not found: {fpath}")
        assert fpath.exists()

    def test_load_without_error(self):
        fpath = DATA_DIR / "Sample - Superstore.xls"
        if not fpath.exists():
            pytest.skip(f"Data file not found: {fpath}")
        try:
            df = pd.read_excel(DATA_DIR / "Sample - Superstore.xls")
        except (UnicodeDecodeError, ValueError):
            df = pd.read_excel(DATA_DIR / "Sample - Superstore.xls", encoding="latin-1")
        assert df is not None

    def test_dataframe_not_empty(self):
        fpath = DATA_DIR / "Sample - Superstore.xls"
        if not fpath.exists():
            pytest.skip(f"Data file not found: {fpath}")
        try:
            df = pd.read_excel(DATA_DIR / "Sample - Superstore.xls")
        except (UnicodeDecodeError, ValueError):
            df = pd.read_excel(DATA_DIR / "Sample - Superstore.xls", encoding="latin-1")
        assert len(df) > 0, "DataFrame is empty"
        assert df.shape[1] > 0, "DataFrame has no columns"

    def test_no_all_null_columns(self):
        fpath = DATA_DIR / "Sample - Superstore.xls"
        if not fpath.exists():
            pytest.skip(f"Data file not found: {fpath}")
        try:
            df = pd.read_excel(DATA_DIR / "Sample - Superstore.xls")
        except (UnicodeDecodeError, ValueError):
            df = pd.read_excel(DATA_DIR / "Sample - Superstore.xls", encoding="latin-1")
        # Filter out trailing "Unnamed:" columns (common CSV artifact)
        real_cols = [c for c in df.columns if not str(c).startswith("Unnamed:")]
        if not real_cols:
            pytest.skip("All columns are unnamed — likely metadata file")
        null_cols = [col for col in real_cols if df[col].isna().all()]
        assert len(null_cols) == 0, f"All-NaN columns: {null_cols}"


class TestPreprocessing:
    """Verify preprocessing steps work correctly."""


    def test_numpy_operations(self):
        import numpy as np
        arr = np.array([1, 2, 3, 4, 5])
        assert arr.mean() == 3.0
        assert arr.std() > 0


class TestModelTraining:
    """Verify model training pipeline."""

    def test_model_instantiation(self):
        from sklearn.linear_model import LinearRegression
        model = LinearRegression()
        assert model is not None
        assert hasattr(model, "fit")
        assert hasattr(model, "predict")

    def test_model_fit(self):
        from sklearn.linear_model import LinearRegression
        import numpy as np
        X = np.random.randn(100, 5)
        y = np.random.randn(100)
        model = LinearRegression()
        model.fit(X, y)
        assert hasattr(model, "predict")

    def test_model_r2(self):
        from sklearn.linear_model import LinearRegression
        from sklearn.metrics import r2_score
        import numpy as np
        np.random.seed(42)
        X = np.random.randn(200, 5)
        y = X @ np.array([1, 2, 3, 4, 5]) + np.random.randn(200) * 0.1
        model = LinearRegression()
        model.fit(X[:150], y[:150])
        preds = model.predict(X[150:])
        r2 = r2_score(y[150:], preds)
        assert r2 > 0.5  # should fit well on linear data


class TestPrediction:
    """Verify prediction outputs."""

    def test_prediction_shape(self):
        from sklearn.linear_model import LinearRegression
        import numpy as np
        X = np.random.randn(200, 5)
        y = np.random.randn(200)
        model = LinearRegression()
        model.fit(X[:150], y[:150])
        preds = model.predict(X[150:])
        assert preds.shape == (50,)

    def test_predictions_are_numeric(self):
        from sklearn.linear_model import LinearRegression
        import numpy as np
        X = np.random.randn(200, 5)
        y = np.random.randn(200)
        model = LinearRegression()
        model.fit(X[:150], y[:150])
        preds = model.predict(X[150:])
        assert np.issubdtype(preds.dtype, np.floating) or np.issubdtype(preds.dtype, np.integer)

    def test_no_nan_predictions(self):
        from sklearn.linear_model import LinearRegression
        import numpy as np
        X = np.random.randn(200, 5)
        y = np.random.randn(200)
        model = LinearRegression()
        model.fit(X[:150], y[:150])
        preds = model.predict(X[150:])
        assert not np.any(np.isnan(preds))

