"""
Tests for: Machine Learning Project 7 - Advandced Hyperparameter Tunning
Auto-generated by Phase 4 test generator.
"""
import pytest
import numpy as np
import pandas as pd
from pathlib import Path

DATA_DIR = Path(__file__).resolve().parent.parent / "data" / "advandced_hyperparameter_tunning"
pytestmark = []
pytestmark.append(pytest.mark.data)
pytestmark.append(pytest.mark.sklearn)


class TestDataLoading:
    """Verify data is available."""

    def test_data_dir_exists(self):
        if not DATA_DIR.exists():
            pytest.skip(f"Data directory not found: {DATA_DIR}")
        assert DATA_DIR.exists()


class TestPreprocessing:
    """Verify preprocessing steps work correctly."""


    def test_train_test_split(self):
        from sklearn.model_selection import train_test_split
        import numpy as np
        X = np.random.randn(100, 5)
        y = np.random.randint(0, 2, 100)
        X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
        assert len(X_train) == 80
        assert len(X_test) == 20
        assert X_train.shape[1] == 5


class TestModelTraining:
    """Verify model training pipeline."""

    def test_model_instantiation(self):
        from sklearn.ensemble import RandomForestClassifier
        model = RandomForestClassifier()
        assert model is not None
        assert hasattr(model, "fit")
        assert hasattr(model, "predict")

    def test_model_fit(self):
        from sklearn.ensemble import RandomForestClassifier
        import numpy as np
        X = np.random.randn(100, 5)
        y = np.random.randint(0, 2, 100)
        model = RandomForestClassifier()
        model.fit(X, y)
        assert hasattr(model, "predict")

    def test_model_score(self):
        from sklearn.ensemble import RandomForestClassifier
        from sklearn.metrics import accuracy_score
        import numpy as np
        X = np.random.randn(200, 5)
        y = np.random.randint(0, 2, 200)
        model = RandomForestClassifier()
        model.fit(X[:150], y[:150])
        preds = model.predict(X[150:])
        score = accuracy_score(y[150:], preds)
        assert 0.0 <= score <= 1.0


class TestPrediction:
    """Verify prediction outputs."""

    def test_prediction_shape(self):
        from sklearn.ensemble import RandomForestClassifier
        import numpy as np
        X = np.random.randn(200, 5)
        y = np.random.randint(0, 2, 200)
        model = RandomForestClassifier()
        model.fit(X[:150], y[:150])
        preds = model.predict(X[150:])
        assert preds.shape == (50,)

    def test_prediction_type(self):
        from sklearn.ensemble import RandomForestClassifier
        import numpy as np
        X = np.random.randn(200, 5)
        y = np.random.randint(0, 2, 200)
        model = RandomForestClassifier()
        model.fit(X[:150], y[:150])
        preds = model.predict(X[150:])
        assert preds.dtype in [np.int32, np.int64, np.float64, np.float32]

    def test_no_nan_predictions(self):
        from sklearn.ensemble import RandomForestClassifier
        import numpy as np
        X = np.random.randn(200, 5)
        y = np.random.randint(0, 2, 200)
        model = RandomForestClassifier()
        model.fit(X[:150], y[:150])
        preds = model.predict(X[150:])
        assert not np.any(np.isnan(preds))

