"""
Tests for: Machine Learning Projects 144 - LSTM Time Series Power Consumption
Auto-generated by Phase 4 test generator.
"""
import pytest
import numpy as np
import pandas as pd
from pathlib import Path

DATA_DIR = Path(__file__).resolve().parent.parent / "data" / "lstm_time_series_power_consumption"
pytestmark = []
pytestmark.append(pytest.mark.data)
pytestmark.append(pytest.mark.sklearn)
pytestmark.append(pytest.mark.keras)
pytestmark.append(pytest.mark.slow)


class TestDataLoading:
    """Verify data is available."""

    def test_data_dir_exists(self):
        if not DATA_DIR.exists():
            pytest.skip(f"Data directory not found: {DATA_DIR}")
        assert DATA_DIR.exists()


class TestPreprocessing:
    """Verify preprocessing steps work correctly."""


    def test_scaler_fit_transform(self):
        from sklearn.preprocessing import MinMaxScaler
        import numpy as np
        X = np.random.randn(100, 5)
        scaler = MinMaxScaler()
        X_scaled = scaler.fit_transform(X)
        assert X_scaled.shape == X.shape
        assert not np.any(np.isnan(X_scaled))


class TestModelTraining:
    """Verify Keras model pipeline."""

    def test_keras_importable(self):
        try:
            from tensorflow import keras
        except ImportError:
            pytest.skip("tensorflow not installed")

    def test_model_build(self):
        try:
            from tensorflow.keras.models import Sequential
            from tensorflow.keras.layers import Dense
        except ImportError:
            pytest.skip("tensorflow not installed")
        model = Sequential([
            Dense(32, activation="relu", input_shape=(10,)),
            Dense(16, activation="relu"),
            Dense(1, activation="sigmoid"),
        ])
        model.compile(optimizer="adam", loss="binary_crossentropy", metrics=["accuracy"])
        assert len(model.layers) == 3

    def test_model_fit_and_predict(self):
        try:
            from tensorflow.keras.models import Sequential
            from tensorflow.keras.layers import Dense
        except ImportError:
            pytest.skip("tensorflow not installed")
        import numpy as np
        model = Sequential([
            Dense(32, activation="relu", input_shape=(10,)),
            Dense(1, activation="sigmoid"),
        ])
        model.compile(optimizer="adam", loss="binary_crossentropy")
        X = np.random.randn(50, 10).astype(np.float32)
        y = np.random.randint(0, 2, 50).astype(np.float32)
        model.fit(X, y, epochs=1, verbose=0)
        preds = model.predict(X[:5], verbose=0)
        assert preds.shape == (5, 1)


class TestPrediction:
    """Verify prediction outputs."""

    def test_prediction_range(self):
        try:
            from tensorflow.keras.models import Sequential
            from tensorflow.keras.layers import Dense
        except ImportError:
            pytest.skip("tensorflow not installed")
        import numpy as np
        model = Sequential([
            Dense(16, activation="relu", input_shape=(10,)),
            Dense(1, activation="sigmoid"),
        ])
        model.compile(optimizer="adam", loss="binary_crossentropy")
        X = np.random.randn(50, 10).astype(np.float32)
        y = np.random.randint(0, 2, 50).astype(np.float32)
        model.fit(X, y, epochs=1, verbose=0)
        preds = model.predict(X[:5], verbose=0)
        assert np.all(preds >= 0) and np.all(preds <= 1)

