"""
Tests for: Machine Learning Projects 129 - Weather Data Clustering using k-Means
Auto-generated by Phase 4 test generator.
"""
import pytest
import numpy as np
import pandas as pd
from pathlib import Path

DATA_DIR = Path(__file__).resolve().parent.parent / "data" / "weather_data_clustering_using_k-means"
pytestmark = []
pytestmark.append(pytest.mark.data)
pytestmark.append(pytest.mark.clustering)


class TestDataLoading:
    """Verify data is available."""

    def test_data_dir_exists(self):
        if not DATA_DIR.exists():
            pytest.skip(f"Data directory not found: {DATA_DIR}")
        assert DATA_DIR.exists()


class TestPreprocessing:
    """Verify preprocessing steps work correctly."""


    def test_scaler_fit_transform(self):
        from sklearn.preprocessing import StandardScaler
        import numpy as np
        X = np.random.randn(100, 5)
        scaler = StandardScaler()
        X_scaled = scaler.fit_transform(X)
        assert X_scaled.shape == X.shape
        assert not np.any(np.isnan(X_scaled))


class TestModelTraining:
    """Verify model training pipeline."""

    def test_model_instantiation(self):
        from sklearn.cluster import KMeans
        model = KMeans(n_clusters=3)
        assert model is not None

    def test_model_fit(self):
        from sklearn.cluster import KMeans
        import numpy as np
        X = np.random.randn(100, 5)
        model = KMeans(n_clusters=3)
        model.fit(X)
        assert hasattr(model, "labels_")
        assert len(model.labels_) == 100

    def test_prediction(self):
        from sklearn.cluster import KMeans
        import numpy as np
        X = np.random.randn(100, 5)
        model = KMeans(n_clusters=3)
        model.fit(X)
        labels = model.predict(X[:10])
        assert labels.shape == (10,)
        assert all(0 <= l < 3 for l in labels)


class TestPrediction:
    """Verify prediction outputs."""

    def test_prediction_shape(self):
        from sklearn.cluster import KMeans
        import numpy as np
        X = np.random.randn(200, 5)
        model = KMeans(n_clusters=3)
        model.fit(X)
        preds = model.predict(X[:50])
        assert preds.shape == (50,)

    def test_prediction_type(self):
        from sklearn.cluster import KMeans
        import numpy as np
        X = np.random.randn(200, 5)
        model = KMeans(n_clusters=3)
        model.fit(X)
        preds = model.predict(X[:10])
        assert preds.dtype in [np.int32, np.int64, np.float64, np.float32]

