artifact_location: file:E:/Github/Machine-Learning-Projects/Computer Vision/Number
  Plate Reader Pro/Source Code/runs/mlflow/420064647549629186
creation_time: 1776252103146
experiment_id: '420064647549629186'
last_update_time: 1776252103146
lifecycle_stage: active
name: E:\Github\Machine-Learning-Projects\Computer Vision\Number Plate Reader Pro\Source
  Code\runs
trace_location: null
workspace: default
