artifact_uri: file:E:/Github/Machine-Learning-Projects/Computer Vision/Document Layout
  Block Detector/Source Code/runs/mlflow/387582139047086988/0778b7540e5a44a393e49bdd4313aae1/artifacts
end_time: 1776244570165
entry_point_name: ''
experiment_id: '387582139047086988'
lifecycle_stage: active
run_id: 0778b7540e5a44a393e49bdd4313aae1
run_name: train
source_name: ''
source_type: 4
source_version: ''
start_time: 1776244536242
status: 3
tags: []
user_id: ahmad
