artifact_location: file:E:/Github/Machine-Learning-Projects/Computer Vision/Parking
  Occupancy Monitor/Source Code/runs/mlflow/680422679382074110
creation_time: 1776190640598
experiment_id: '680422679382074110'
last_update_time: 1776190640598
lifecycle_stage: active
name: E:\Github\Machine-Learning-Projects\Computer Vision\Parking Occupancy Monitor\Source
  Code\runs
trace_location: null
workspace: default
