artifact_uri: file:E:/Github/Machine-Learning-Projects/Computer Vision/Sports Ball
  Possession Tracker/Source Code/runs/mlflow/996460333976139282/e844d97feae9434aa2ca774d32e0e0f1/artifacts
end_time: 1776245161948
entry_point_name: ''
experiment_id: '996460333976139282'
lifecycle_stage: active
run_id: e844d97feae9434aa2ca774d32e0e0f1
run_name: train
source_name: ''
source_type: 4
source_version: ''
start_time: 1776245091859
status: 3
tags: []
user_id: ahmad
