artifact_location: file:E:/Github/Machine-Learning-Projects/Computer Vision/Retail
  Shelf Stockout Detector/Source Code/runs/mlflow/0
creation_time: 1776189625080
experiment_id: '0'
last_update_time: 1776189625080
lifecycle_stage: active
name: Default
trace_location: null
workspace: default
