artifact_location: file:E:/Github/Machine-Learning-Projects/Computer Vision/Drone
  Ship OBB Detector/Source Code/runs/mlflow/343805799057863484
creation_time: 1776243924459
experiment_id: '343805799057863484'
last_update_time: 1776243924459
lifecycle_stage: active
name: E:\Github\Machine-Learning-Projects\Computer Vision\Drone Ship OBB Detector\Source
  Code\runs
trace_location: null
workspace: default
