artifact_uri: file:E:/Github/Machine-Learning-Projects/Computer Vision/PPE Compliance
  Monitor/Source Code/runs/mlflow/320489081518351585/9d05c45f630d41f8a980680ef5cfde66/artifacts
end_time: 1776190304488
entry_point_name: ''
experiment_id: '320489081518351585'
lifecycle_stage: active
run_id: 9d05c45f630d41f8a980680ef5cfde66
run_name: ppe_detect
source_name: ''
source_type: 4
source_version: ''
start_time: 1776190265761
status: 3
tags: []
user_id: ahmad
