artifact_location: file:E:/Github/Machine-Learning-Projects/Computer Vision/Document
  Layout Block Detector/Source Code/runs/mlflow/387582139047086988
creation_time: 1776244532141
experiment_id: '387582139047086988'
last_update_time: 1776244532141
lifecycle_stage: active
name: E:\Github\Machine-Learning-Projects\Computer Vision\Document Layout Block Detector\Source
  Code\runs
trace_location: null
workspace: default
