artifact_uri: file:E:/Github/Machine-Learning-Projects/Computer Vision/Conveyor Part
  Defect Detector/Source Code/runs/mlflow/371158837269195364/31c08bcc5b0f4f1bbeda782b1ae51689/artifacts
end_time: 1776191722981
entry_point_name: ''
experiment_id: '371158837269195364'
lifecycle_stage: active
run_id: 31c08bcc5b0f4f1bbeda782b1ae51689
run_name: train
source_name: ''
source_type: 4
source_version: ''
start_time: 1776191688307
status: 3
tags: []
user_id: ahmad
