artifact_location: file:E:/Github/Machine-Learning-Projects/Computer Vision/PPE Compliance
  Monitor/Source Code/runs/mlflow/320489081518351585
creation_time: 1776190264971
experiment_id: '320489081518351585'
last_update_time: 1776190264971
lifecycle_stage: active
name: E:\Github\Machine-Learning-Projects\Computer Vision\PPE Compliance Monitor\Source
  Code\runs
trace_location: null
workspace: default
