artifact_location: file:E:/Github/Machine-Learning-Projects/Computer Vision/Traffic
  Violation Analyzer/Source Code/runs/mlflow/134989453050397025
creation_time: 1776191122901
experiment_id: '134989453050397025'
last_update_time: 1776191122901
lifecycle_stage: active
name: E:\Github\Machine-Learning-Projects\Computer Vision\Traffic Violation Analyzer\Source
  Code\runs
trace_location: null
workspace: default
