artifact_location: file:E:/Github/Machine-Learning-Projects/Computer Vision/Parking
  Occupancy Monitor/Source Code/runs/mlflow/0
creation_time: 1776190640570
experiment_id: '0'
last_update_time: 1776190640570
lifecycle_stage: active
name: Default
trace_location: null
workspace: default
