artifact_location: file:E:/Github/Machine-Learning-Projects/Computer Vision/Sports
  Ball Possession Tracker/Source Code/runs/mlflow/996460333976139282
creation_time: 1776245087962
experiment_id: '996460333976139282'
last_update_time: 1776245087962
lifecycle_stage: active
name: E:\Github\Machine-Learning-Projects\Computer Vision\Sports Ball Possession Tracker\Source
  Code\runs
trace_location: null
workspace: default
